project_id = "ffzrezqwdlafysmhlzwq"

[functions.analyze-beats]
verify_jwt = false

[functions.apply-video-effects]
verify_jwt = false

[functions.transloadit-webhook]
verify_jwt = false

[functions.video-encode]
verify_jwt = false

[functions.video-webhook]
verify_jwt = false

[functions.video-proxy]
verify_jwt = false
